env:
  browser: true
  es6: true
  node: false
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  $: true
  RoseBud: readonly
parserOptions:
  ecmaVersion: 2018
rules: 
    noConsole: off
    semi:
        - 2
        - always
plugins:
    - "script-tags"
